# ------------------------------
# Verdaccio Caching Proxy Config
# ------------------------------

storage: /verdaccio/storage

secret: SECRET_TOKEN

web:
  title: Verdaccio Cache Proxy
  enable: false

auth:
  htpasswd:
    file: /verdaccio/htpasswd
    max_users: 1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@myorg/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

log:
  type: stdout
  format: pretty
  level: http

listen: 0.0.0.0:4873

middlewares:
  audit:
    enabled: true
