 
---
# Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: verdaccio-cert
  namespace: yahyeapps
spec:
  secretName: verdaccio-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - registry.yahyasimple.com

 
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verdaccio-deployment
  namespace: yahyeapps
  labels:
    app: verdaccio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verdaccio-deployment
  template:
    metadata:
      labels:
        app: verdaccio-deployment
    spec:
      containers:
        - name: webhook
          image: "{{IMAGE}}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              name: http
          env:
            - name: R2_BUCKET
              valueFrom:
                secretKeyRef:
                  name: webhook-secrets
                  key: R2_BUCKET
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: webhook-secrets
                  key: S3_SECRET_ACCESS_KEY
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: webhook-secrets
                  key: S3_ACCESS_KEY_ID
            - name: R2_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: webhook-secrets
                  key: R2_ENDPOINT
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: webhook-secrets
                  key: PORT
      
      imagePullSecrets:
        - name: my-dockerhub-secret

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: verdaccio-service
  namespace: yahyeapps
  labels:
    app: verdaccio-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: verdaccio-deployment

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: verdaccio-ingress
  namespace: yahyeapps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - registry.yahyasimple.com
      secretName: verdaccio-cert-tls
  rules:
    - host: "registry.yahyasimple.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: verdaccio-service
                port:
                  number: 80
